CREATE TABLE IF NOT EXISTS qless_user (
	username varchar(25) NOT NULL PRIMARY KEY,
	fname varchar(30) NOT NULL,
	lname varchar(30) NOT NULL,
	email varchar(50) NOT NULL,
	password char(64) NOT NULL,
	user_id int UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT valid_email CHECK (email ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
);


CREATE TABLE IF NOT EXISTS team (
	team_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(30) UNIQUE NULL,
	employees integer[],
	categories varchar[]
);

CREATE TABLE IF NOT EXISTS employee (
	employee_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int NOT NULL,
	team_id  int,
	team_name varchar(30),
	is_supervisor boolean NOT NULL,
	CONSTRAINT fk_employee_userId FOREIGN KEY(user_id) REFERENCES qless_user(user_id),
	CONSTRAINT fk_employee_teamId FOREIGN KEY(team_id) REFERENCES team(team_id),
	CONSTRAINT fk_employee_teamName FOREIGN KEY(team_name) REFERENCES team(name)
);


CREATE TABLE IF NOT EXISTS category (
	category_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	team_id int NOT NULL,
	name varchar(30) NOT NULL,
	etc int NOT NULL,
	priority varchar(20) NOT NULL,
	CONSTRAINT fk_category_teamId FOREIGN KEY(team_id) REFERENCES team(team_id)
);


CREATE TABLE IF NOT EXISTS ticket (
	ticket_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int NOT NULL,
	employee_id int,
	category_id int NOT NULL,
	state varchar(20) NOT NULL,
	create_date timestamp NOT NULL,
	update_date timestamp,
	solved_date timestamp,
	attachments bytea,
	CONSTRAINT fk_ticket_userId FOREIGN KEY(user_id) REFERENCES qless_user(user_id),
	CONSTRAINT fk_ticket_employeeId FOREIGN KEY(employee_id) REFERENCES employee(employee_id),
	CONSTRAINT fk_ticket_categoryId FOREIGN KEY(category_id) REFERENCES category(category_id)
);

CREATE TABLE IF NOT EXISTS message (
	message_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int NOT NULL, 
	employee_id int,
	ticket_id int NOT NULL,
	sent_time timestamp NOT NULL,
	body varchar(150) NOT NULL,
	CONSTRAINT fk_message_ticketId FOREIGN KEY(ticket_id) REFERENCES ticket(ticket_id)
);
