DROP TABLE IF EXISTS qless_user CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS team CASCADE ;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS message CASCADE;