CREATE TABLE IF NOT EXISTS qless_user (
	username varchar(25) NOT NULL PRIMARY KEY,
	fname varchar(30) NOT NULL,
	lname varchar(30) NOT NULL,
	email varchar(50) NOT NULL,
	password char(64) NOT NULL,
	user_id int UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT valid_email CHECK (email ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
);

CREATE TABLE IF NOT EXISTS employee (
	employee_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	is_supervisor boolean NOT NULL,
	CONSTRAINT fk_employee_id FOREIGN KEY(employee_id) REFERENCES qless_user(user_id)
);

CREATE TABLE IF NOT EXISTS team (
	team_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(30),
	CONSTRAINT fk_team_id FOREIGN KEY(team_id) REFERENCES employee(employee_id)
);

CREATE TABLE IF NOT EXISTS category (
	category_id int PRIMARY KEY,
	name varchar(30) NOT NULL,
	etc int NOT NULL,
	priority varchar(20) NOT NULL,
	CONSTRAINT fk_team_id FOREIGN KEY(category_id) REFERENCES team(team_id),
);


CREATE TABLE IF NOT EXISTS ticket (
	ticket_id int PRIMARY KEY,
	state varchar(20) NOT NULL,
	category varchar(30) NOT NULL,
	create_date DATE NOT NULL,
	update_date DATE,
	solved_date DATE,
	CONSTRAINT fk_ticket_id FOREIGN KEY(ticket_id) REFERENCES qless_user(user_id),
	CONSTRAINT fk_category_id FOREIGN KEY(ticket_id) REFERENCES category(category_id)
);

CREATE TABLE IF NOT EXISTS message (
	message_id int PRIMARY KEY,
	created_by varchar(25) NOT NULL,
	solved_by varchar(25) NOT NULL,
	CONSTRAINT fk_user_id FOREIGN KEY(created_by) REFERENCES qless_user(username),
	CONSTRAINT fk_employee_id FOREIGN KEY(solved_by) REFERENCES qless_user(username),
	CONSTRAINT fk_ticket_id FOREIGN KEY(message_id) REFERENCES ticket(ticket_id)
);
